export interface ContingenciaCatalogoInicial {
  codigo: string;
  nombre: string;
  hoja_excel: string;
  columna_excel: string;
  items: string[];
}

export const ESTACIONES_LINEA_1 = [
  "Villa El Salvador",
  "Parque Industrial",
  "Pumacahua",
  "Villa Maria",
  "Maria Auxiliadora",
  "San Juan",
  "Atocongo",
  "Jorge Chavez",
  "Ayacucho",
  "Cabitos",
  "Angamos",
  "San Borja Sur",
  "La Cultura",
  "Arriola",
  "Gamarra",
  "Miguel Grau",
  "El Angel",
  "Presbitero Maestro",
  "Caja de Agua",
  "Piramide del Sol",
  "Los Jardines",
  "Los Postes",
  "San Carlos",
  "San Martin",
  "Santa Rosa",
  "Bayovar",
];

export const CONTINGENCIA_CATALOGOS_INICIALES: ContingenciaCatalogoInicial[] = [
  {
    codigo: "tipo_de_evento",
    nombre: "TIPO DE EVENTO",
    hoja_excel: "Base de datos",
    columna_excel: "D",
    items: ["Accidente ", "Problemas de salud"],
  },
  {
    codigo: "lugar_del_evento",
    nombre: "LUGAR DEL EVENTO",
    hoja_excel: "Base de datos",
    columna_excel: "E",
    items: [
      "NA",
      "PATIO VES",
      "PATIO BAY",
      ...ESTACIONES_LINEA_1,
    ],
  },
  {
    codigo: "lugar_exacto_del_evento",
    nombre: "LUGAR EXACTO DEL EVENTO",
    hoja_excel: "Base de datos",
    columna_excel: "F",
    items: [
      "Anden par",
      "Anden impar",
      "NA",
      "Escaleras Fijas Par",
      "Escaleras Fijas Impar",
      "Escaleras Electricas par",
      "Escaleras Electricas impar",
      "Hall",
      "SSHH",
      "Explanada",
      "Torniquetes",
      "TVM",
      "Exteriores",
      "Zona no paga ",
      "Pasarela",
      "Ascensor Interno Par",
      "Ascensor Interno Impar",
      "Ascensor Externo Par",
      "Ascensor Externo Impar",
      "Salvaescaleras Par",
      "Salvaescaleras Impar",
      "Interior de Tren 1",
      "Interior de Tren 2",
      "Interior de Tren 3",
      "Interior de Tren 4",
      "Interior de Tren 5",
      "Interior de Tren 6",
      "Interior de Tren 7",
      "Interior de Tren 8",
      "Interior de Tren 9",
      "Interior de Tren 10",
      "Interior de Tren 11",
      "Interior de Tren 12",
      "Interior de Tren 13",
      "Interior de Tren 14",
      "Interior de Tren 15",
      "Interior de Tren 16",
      "Interior de Tren 17",
      "Interior de Tren 18",
      "Interior de Tren 19",
      "Interior de Tren 20",
      "Interior de Tren 21",
      "Interior de Tren 22",
      "Interior de Tren 23",
      "Interior de Tren 24",
      "Interior de Tren 25",
      "Interior de Tren 26",
      "Interior de Tren 27",
      "Interior de Tren 28",
      "Interior de Tren 29",
      "Interior de Tren 30",
      "Interior de Tren 31",
      "Interior de Tren 32",
      "Interior de Tren 33",
      "Interior de Tren 34",
      "Interior de Tren 35",
      "Interior de Tren 36",
      "Interior de Tren 37",
      "Interior de Tren 38",
      "Interior de Tren 39",
      "Interior de Tren 40",
      "Interior de Tren 41",
      "Interior de Tren 42",
      "Interior de Tren 43",
      "Interior de Tren 44",
      "Interior del Tren",
    ],
  },
  {
    codigo: "quien_reporta_primer_reporte",
    nombre: "QUIEN REPORTA (PRIMER REPORTE)",
    hoja_excel: "Base de datos",
    columna_excel: "G",
    items: [
      "PASAJERO",
      "SPAA",
      "AGENTE DE ESTACION",
      "AVP",
      "CENTRO DE CONTROL",
      "LIMPIEZA",
      "COLABORADOR",
      "PNP",
      "TERCEROS",
      "CONDUCTOR",
      "PCO",
      "SPAA-PILOTO",
    ],
  },
  {
    codigo: "medio_de_comunicacion_del_primer_reporte",
    nombre: "MEDIO DE COMUNICACIÓN DEL PRIMER REPORTE",
    hoja_excel: "Base de datos",
    columna_excel: "H",
    items: [
      "RADIO TETRA",
      "INTERCOMUNICADOR DE EMERGENCIA",
      "TELEFONO DE EMERGENCIA",
      "TELEFONO IP",
      "CELULAR",
      "INTERCOMUNICADOR DE TREN",
    ],
  },
  {
    codigo: "estado_del_usuario_reportado",
    nombre: "ESTADO DEL USUARIO REPORTADO",
    hoja_excel: "Base de datos",
    columna_excel: "I",
    items: ["CONSCIENTE", "INCONSCIENTE"],
  },
  {
    codigo: "acepta_atencion",
    nombre: "ACEPTA ATENCION",
    hoja_excel: "Base de datos",
    columna_excel: "J",
    items: ["SI", "NO"],
  },
  {
    codigo: "atencion_inicial",
    nombre: "ATENCION INICIAL",
    hoja_excel: "Base de datos",
    columna_excel: "K",
    items: ["SPPA", "COLABORADOR", "PNP FERROVIARIO", "AGENTE DE ESTACION"],
  },
  {
    codigo: "atencion_final",
    nombre: "ATENCION FINAL",
    hoja_excel: "Base de datos",
    columna_excel: "L",
    items: ["AGENTE DE ESTACION", "BOMBEROS ", "PARTICULAR", "PERSONAL DE SALUD EXTERNO", "PNP", "SAMU", "SPAA"],
  },
  {
    codigo: "nivel_inicial",
    nombre: "NIVEL INICIAL",
    hoja_excel: "Base de datos",
    columna_excel: "M",
    items: ["1", "2", "3", "CONCAR", "ADENDA NIVEL 2", "ADENDA NIVEL 3"],
  },
  {
    codigo: "nivel_final",
    nombre: "NIVEL FINAL",
    hoja_excel: "Base de datos",
    columna_excel: "N",
    items: ["1", "2", "3", "CONCAR", "ADENDA NIVEL 2", "ADENDA NIVEL 3"],
  },
  {
    codigo: "estacion_de_partida_del_spaa",
    nombre: "Estación de Partida del SPAA",
    hoja_excel: "Base de datos",
    columna_excel: "S",
    items: ["MISMA ESTACION", ...ESTACIONES_LINEA_1],
  },
  {
    codigo: "medio_de_transporte_del_spaa",
    nombre: "Medio de transporte del SPAA",
    hoja_excel: "Base de datos",
    columna_excel: "T",
    items: ["AMBULANCIA SPAA", "MISMA ESTACIÓN", "TREN", "BOMBEROS ", "SAMU", "PNP", "TAXI", "PARTICULAR"],
  },
  {
    codigo: "trasladado_por",
    nombre: "TRASLADADO POR",
    hoja_excel: "Base de datos",
    columna_excel: "U",
    items: ["AMBULANCIA SPAA", "BOMBEROS ", "SAMU", "PNP", "TAXI", "PARTICULAR", "NO REQUIERE TRASLADO ", "DESISTE TRASLADO"],
  },
  {
    codigo: "estacion_de_partida_de_la_ambulancia",
    nombre: "ESTACIÓN DE PARTIDA DE LA AMBULANCIA",
    hoja_excel: "Base de datos",
    columna_excel: "S",
    items: ["MISMA ESTACION", ...ESTACIONES_LINEA_1],
  },
  {
    codigo: "estacion_de_llegada_de_la_ambulancia",
    nombre: "ESTACIÓN DE LLEGADA DE LA AMBULANCIA",
    hoja_excel: "Base de datos",
    columna_excel: "W",
    items: [
      "MISMA ESTACION",
      "Patio VES",
      "Patio BAY",
      ...ESTACIONES_LINEA_1,
      "Tren N° 1",
      "Tren N° 2",
      "Tren N° 3",
      "Tren N° 4",
      "Tren N° 5",
      "Tren N° 6",
      "Tren N° 7",
      "Tren N° 8",
      "Tren N° 9",
      "Tren N° 10",
      "Tren N° 11",
      "Tren N° 12",
      "Tren N° 13",
      "Tren N° 14",
      "Tren N° 15",
      "Tren N° 16",
      "Tren N° 17",
      "Tren N° 18",
      "Tren N° 19",
      "Tren N° 20",
      "Tren N° 21",
      "Tren N° 22",
      "Tren N° 23",
      "Tren N° 24",
      "Tren N° 25",
      "Tren N° 26",
      "Tren N° 27",
      "Tren N° 28",
      "Tren N° 29",
      "Tren N° 30",
      "Tren N° 31",
      "Tren N° 32",
      "Tren N° 33",
      "Tren N° 34",
      "Tren N° 35",
      "Tren N° 36",
      "Tren N° 37",
      "Tren N° 38",
      "Tren N° 39",
      "Tren N° 40",
      "Tren N° 41",
      "Tren N° 42",
      "Tren N° 43",
      "Tren N° 44",
      "Tren N° 45",
    ],
  },
  {
    codigo: "sexo",
    nombre: "SEXO",
    hoja_excel: "Base de datos",
    columna_excel: "AI",
    items: ["M", "F"],
  },
  {
    codigo: "reporte_del_pco",
    nombre: "REPORTE DEL PCO",
    hoja_excel: "Base de datos",
    columna_excel: "AL",
    items: ["Pasajero inconsciente", "Atasco en puertas de coche", "Pasajero con Convulsiones", "Pasajero Asistido", "Caída", "Colaborador UNNA"],
  },
  {
    codigo: "reporte_al_cliente",
    nombre: "REPORTE AL CLIENTE",
    hoja_excel: "Base de datos",
    columna_excel: "AM",
    items: [
      "NA",
      "Atencion cancelada",
      "Caída",
      "Convulsión",
      "Contusión / Traumatismo",
      "Corte ",
      "Desvanecido",
      "Dolor de cabeza",
      "Dolor muscular",
      "Dolor torácico",
      "Enfermedad",
      "Esguince",
      "Fiebre",
      "Fracturas",
      "Hemorragias",
      "Herida",
      "Intoxicación",
      "Impacto físico",
      "Otros",
      "Problema respiratorio",
      "Problemas cardiacos",
      "Problemas gastrointestinales / estomacales",
      "Problemas ginecológico / Menstruales",
      "Problemas neurológicos",
      "Problemas psiquiátricos",
    ],
  },
  {
    codigo: "diagnostico_presuntivo",
    nombre: "DIAGNOSTICO PRESUNTIVO",
    hoja_excel: "Base de datos",
    columna_excel: "AN",
    items: [
      "NA",
      "Accidente cerebro vascular ACV",
      "Amenaza de aborto",
      "Amenorrea",
      "Anemia",
      "Angina",
      "Apendicitis",
      "Ausencia de signos vitales",
      "Broncoespasmos",
      "Cefalea",
      "Colecistitis aguda",
      "Cólicos menstruales",
      "Contusión / Traumatismo",
      "Corte ",
      "Crisis asmática",
      "Crisis convulsiva",
      "Crisis de ansiedad",
      "Crisis Migraña",
      "Desmayo",
      "Diabetes",
      "Dislipidemia",
      "Dismenorrea",
      "Dolor Abdominal",
      "Nauseas",
      "Dolor torácico",
      "Epilepsia",
      "Esguince",
      "Esquizofrenia",
      "Estrés",
      "Faringitis aguda",
      "Descartar Fractura",
      "Hemorragias",
      "Herida",
      "Gasteroenterocolitis aguda",
      "Gastritis",
      "Ginecorragia",
      "Hipertensión arterial",
      "Hipotensión arterial",
      "IMA (Infarto al Miocardio)",
      "Intoxicación alimentaria",
      "Intoxicación medicamentosa",
      "Lipotimia",
      "Mareos",
      "Neumonía",
      "Osteocrondritis",
      "Otros",
      "Parto",
      "Pródromos de parto",
      "Resfrió Común",
      "Sincope",
      "Síndrome Emetico",
      "Síndrome febril",
      "Síndrome vertiginoso",
      "Taquicardia",
      "Trastorno del sensorio",
      "Tuberculosis",
      "Vómitos",
    ],
  },
  {
    codigo: "zona_de_la_lesion",
    nombre: "ZONA DE LA LESION",
    hoja_excel: "Base de datos",
    columna_excel: "AP",
    items: [
      "Abdomen",
      "Cabeza",
      "Codo derecho",
      "Codo izquierdo",
      "Epistaxis",
      "Espalda",
      "Mano derecha",
      "Mano Izquierda",
      "Otro",
      "Pie derecho",
      "Pie Izquierdo",
      "Pierna derecha",
      "Pierna izquierda",
      "Policontuso",
      "Rodilla derecha",
      "Rodilla izquierda",
      "Tobillo derecho",
      "Tobillo izquierdo",
      "Gastritis",
      "Gastroenterocolitis",
      "Gestante",
      "Nariz",
      "NA ",
    ],
  },
  {
    codigo: "categoria_de_paciente",
    nombre: "CATEGORIA DE PACIENTE",
    hoja_excel: "Base de datos",
    columna_excel: "AQ",
    items: ["Colaborador UNNA", "Colaborador Tercero", "Otro", "Proveedor", "Transeúnte", "Pasajero"],
  },
  {
    codigo: "tipo_de_declaracion_jurada",
    nombre: "TIPO DE DECLARACIÓN JURADA",
    hoja_excel: "Base de datos",
    columna_excel: "AS",
    items: ["NA", "A", "B"],
  },
  {
    codigo: "extranjero",
    nombre: "EXTRANJERO",
    hoja_excel: "Base de datos",
    columna_excel: "AV",
    items: ["si", "no"],
  },
  {
    codigo: "estacion_de_origen_del_usuario",
    nombre: "ESTACIÓN DE ORIGEN DEL USUARIO",
    hoja_excel: "Base de datos",
    columna_excel: "AW",
    items: [
      "NA",
      ...ESTACIONES_LINEA_1,
    ],
  },
  {
    codigo: "estacion_de_destino_del_usuario",
    nombre: "ESTACION DE DESTINO DEL USURIO",
    hoja_excel: "Base de datos",
    columna_excel: "AX",
    items: [
      "NA",
      ...ESTACIONES_LINEA_1,
    ],
  },
  {
    codigo: "acompanante",
    nombre: "ACOMPAÑANTE",
    hoja_excel: "Base de datos",
    columna_excel: "AY",
    items: ["NA", "ACCIDENTE", "ENFERMEDAD"],
  },
];

export const CONTINGENCIA_CATALOGOS_POR_CAMPO: Record<string, string> = {
  tipo_evento: "tipo_de_evento",
  lugar_evento: "lugar_del_evento",
  lugar_exacto_evento: "lugar_exacto_del_evento",
  quien_reporta: "quien_reporta_primer_reporte",
  medio_comunicacion_primer_reporte: "medio_de_comunicacion_del_primer_reporte",
  estado_usuario_reportado: "estado_del_usuario_reportado",
  acepta_atencion: "acepta_atencion",
  atencion_inicial: "atencion_inicial",
  atencion_final: "atencion_final",
  nivel_inicial: "nivel_inicial",
  nivel_final: "nivel_final",
  estacion_partida_spaa: "estacion_de_partida_del_spaa",
  medio_transporte_spaa: "medio_de_transporte_del_spaa",
  trasladado_por: "trasladado_por",
  estacion_partida_ambulancia: "estacion_de_partida_de_la_ambulancia",
  estacion_llegada_ambulancia: "estacion_de_llegada_de_la_ambulancia",
  sexo: "sexo",
  categoria_paciente: "categoria_de_paciente",
  extranjero: "extranjero",
  estacion_origen_usuario: "estacion_de_origen_del_usuario",
  estacion_destino_usuario: "estacion_de_destino_del_usuario",
  acompanante: "acompanante",
  reporte_pco: "reporte_del_pco",
  reporte_cliente: "reporte_al_cliente",
  diagnostico_presuntivo: "diagnostico_presuntivo",
  zona_lesion: "zona_de_la_lesion",
  tipo_declaracion_jurada: "tipo_de_declaracion_jurada",
};
