// Catálogos maestros extraídos de "Base para proyecto plataforma SOP.xlsm"
// Fuente: hoja "BD" (tabla dinámica de casos SOP) y hoja "LISTA DE EVENTOS"
// (tabla dinámica de eventos operativos). Cada grupo documenta su columna
// de origen y el nivel de confianza de la lista.

export interface CatalogItem {
  codigo?: string;
  nombre: string;
  descripcion?: string;
}

export interface CatalogGroup {
  codigo: string;
  nombre: string;
  descripcion: string;
  items: CatalogItem[];
}

export const CATALOGOS: CatalogGroup[] = [
  // ── Hoja "BD" ────────────────────────────────────────────────────────
  {
    codigo: "ESTADO_HALLAZGO",
    nombre: "Estado Hallazgo",
    descripcion:
      "BD!Estado Hallazgo. 'Cerrado' y 'En Proceso' vienen confirmados por la tabla dinámica del cliente. 'Recepción' se usa como estado inicial para un caso recién creado desde el módulo Reporte. Los demás valores (no vienen del CSV) son las etapas reales del workflow de Gestión de Casos, verificadas contra el perfil Seguridad Operativa de sigma-l1-metromet.vercel.app (tabs de la bandeja de casos + stepper de 7 etapas del detalle de caso). 'En Proceso' se mantiene solo por compatibilidad con casos ya sembrados; el módulo de Gestión de Casos usa los estados granulares nuevos.",
    items: [
      { nombre: "Recepción" },
      { nombre: "Evaluación" },
      { nombre: "Pendiente de Información" },
      { nombre: "Investigación" },
      { nombre: "Plan de Acción" },
      { nombre: "Ejecución" },
      { nombre: "Prórroga Solicitada" },
      { nombre: "Verificación" },
      { nombre: "Cerrado" },
      { nombre: "Rechazado" },
      { nombre: "En Proceso" },
    ],
  },
  {
    codigo: "PROCEDENCIA",
    nombre: "Procedencia",
    descripcion: "BD!Procedencia.",
    items: [{ nombre: "Incidencias" }, { nombre: "Auditoria SSOMA" }],
  },
  {
    codigo: "TIPO_CASO",
    nombre: "Tipo",
    descripcion: "BD!Tipo (clasificación general del hallazgo).",
    items: [{ nombre: "No Conformidad" }, { nombre: "Observación" }],
  },
  {
    codigo: "TIPO_SOP",
    nombre: "Tipo SOP",
    descripcion: "BD!Tipo SOP.",
    items: [
      { nombre: "Hallazgo" },
      { nombre: "Incidente" },
      { nombre: "Reporte Voluntario" },
      { nombre: "Accidente" },
    ],
  },
  {
    codigo: "SUBTIPO_SOP",
    nombre: "Subtipo SOP",
    descripcion:
      "BD!Subtipo SOP. AVISO: la tabla dinámica etiqueta esta lista de 15 valores como 'Subtipo SOP', pero por su contenido (Atrapamiento, Caída, Descarrilamiento...) se leen como categorías de PELIGRO, no de subtipo. El único caso real visto usa 'Incumplimiento Operativo', que no está en esa lista de 15 — se agregó aparte porque es un valor confirmado por el dato real. Pendiente de confirmar con el cliente si hay una columna desalineada.",
    items: [
      { nombre: "Atrapamiento" },
      { nombre: "Caída" },
      { nombre: "Caida o rotura de línea de contacto" },
      { nombre: "Condiciones del entorno" },
      { nombre: "Descarrilamiento" },
      { nombre: "Ejecución inadeacuada de procedimiento" },
      { nombre: "Error en funcionamiento de sistemas de tren" },
      { nombre: "Falta de, o deficiente control de, o ausencia de, herramientas y equipos calibrados" },
      {
        nombre:
          "Falta de, o deficientes, programas de mantenimiento (incluyendo datos de mantenimiento imprecisos o errores de transcripción en la creación de órdenes de trabajo)",
      },
      { nombre: "Falta de, o inadecuadas, instrucciones de los equipamientos, herramientas y equipos de seguridad operacional" },
      { nombre: "Falta o deficiencia de comunicación" },
      { nombre: "Incumplimiento Operativo" }, // confirmado por el caso real, no venía en la lista de 15
      { nombre: "Indisponibilidad, o mal funcionamiento reiterativo de equipos e instrumentos necesarios para las carreras comerciales o emergencias" },
      { nombre: "Instalaciones deficientes (espacio inadecuado, estación en mal estado)" },
      { nombre: "Movimiento de equipos auxiliares" },
      { nombre: "Objecto extraño en vía" },
      { nombre: "Talonamiento" },
      { nombre: "Otro" },
    ],
  },
  {
    codigo: "ANALISIS_RIESGO",
    nombre: "Análisis de riesgo",
    descripcion:
      "BD!Análisis de riesgo. Matriz de riesgo clásica (código alfanumérico + nivel). El 'codigo' es el identificador de matriz (1A..4E) y el 'orden' preserva el orden original de severidad.",
    items: [
      { codigo: "1A", nombre: "Inaceptable" },
      { codigo: "1B", nombre: "Inaceptable" },
      { codigo: "1C", nombre: "Inaceptable" },
      { codigo: "2A", nombre: "Inaceptable" },
      { codigo: "2B", nombre: "Inaceptable" },
      { codigo: "1D", nombre: "No deseable" },
      { codigo: "2C", nombre: "No deseable" },
      { codigo: "3A", nombre: "No Deseable" },
      { codigo: "3B", nombre: "No Deseable" },
      { codigo: "1E", nombre: "Aceptable con revisión por la gerencia" },
      { codigo: "2D", nombre: "Aceptable con revisión por la gerencia" },
      { codigo: "2E", nombre: "Aceptable con revisión por la gerencia" },
      { codigo: "3C", nombre: "Aceptable con revisión por la gerencia" },
      { codigo: "3D", nombre: "Aceptable con revisión por la gerencia" },
      { codigo: "3E", nombre: "Aceptable con revisión por la gerencia" },
      { codigo: "4A", nombre: "Aceptable con revisión por la gerencia" },
      { codigo: "4B", nombre: "Aceptable sin revisión por la gerencia" },
      { codigo: "4C", nombre: "Aceptable sin revisión por la gerencia" },
      { codigo: "4D", nombre: "Aceptable sin revisión por la gerencia" },
      { codigo: "4E", nombre: "Aceptable sin revisión por la gerencia" },
    ],
  },
  {
    codigo: "ESTADO_PLAN",
    nombre: "Estado Plan de acción",
    descripcion:
      "BD!Estado Plan de acción. La tabla dinámica original tenía un error #REF! en la mayoría de esta columna; solo 'Cerrado' quedó legible. Los demás valores (no vienen del CSV) son los estados reales del ciclo de vida de un plan de acción dentro del módulo de Gestión de Casos: se crea 'Pendiente', SO lo 'Enviado' al área responsable, el Jefe de Área lo 'Aceptado'/'Rechazado', y mientras se ejecuta queda 'En Ejecución' hasta 'Cerrado'.",
    items: [
      { nombre: "Pendiente" },
      { nombre: "Enviado" },
      { nombre: "Aceptado" },
      { nombre: "Rechazado" },
      { nombre: "En Ejecución" },
      { nombre: "Cerrado" },
    ],
  },
  {
    codigo: "ESTADO_ACTIVIDAD",
    nombre: "Estado Actividad",
    descripcion:
      "No viene del CSV — estado de cada actividad dentro de un plan de acción (tabla actividades_plan), verificado contra el perfil Jefe de Área del prototipo desplegado ('Pendiente/En progreso/Completado').",
    items: [{ nombre: "Pendiente" }, { nombre: "En progreso" }, { nombre: "Completado" }],
  },

  // ── Hoja "LISTA DE EVENTOS" ──────────────────────────────────────────
  {
    codigo: "RANGO_HORARIO",
    nombre: "Rango horario",
    descripcion: "LISTA DE EVENTOS!Rango horario. 12 bloques de 2 horas.",
    items: [
      { nombre: "00:00 - 01:59" },
      { nombre: "02:00 - 03:59" },
      { nombre: "04:00 - 05:59" },
      { nombre: "06:00 - 07:59" },
      { nombre: "08:00 - 09:59" },
      { nombre: "10:00 - 11:59" },
      { nombre: "12:00 - 13:59" },
      { nombre: "14:00 - 15:59" },
      { nombre: "16:00 - 17:59" },
      { nombre: "18:00 - 19:59" },
      { nombre: "20:00 - 21:59" },
      { nombre: "22:00 - 23:59" },
    ],
  },
  {
    codigo: "TIPO_INCIDENTE_OPERATIVO",
    nombre: "Tipo de incidente operativo",
    descripcion: "LISTA DE EVENTOS!Tipo de incidente operativo. Taxonomía operacional real, distinta de 'Tipo SOP'.",
    items: [
      { nombre: "AMENAZA SUICIDA" },
      { nombre: "ARROLLAMIENTO" },
      { nombre: "ATRAPAMIENTO" },
      { nombre: "ATRAPAMIENTO-DJ" },
      { nombre: "ATROPELLO" },
      { nombre: "CAIDA EN ESTACIÓN" },
      { nombre: "CAIDA EN ESTACIÓN-DJ" },
      { nombre: "COLISION MR -OBSTÁCULO" },
      { nombre: "DESALOJO" },
      { nombre: "DESCARRILAMIENTO" },
      { nombre: "IMPACTO FÍSICO" },
      { nombre: "IMPACTO FÍSICO-DJ" },
      { nombre: "INGRESO A LA VÍA" },
      { nombre: "INTENTO DE SUICIDIO" },
      { nombre: "NO ABRE PUERTAS" },
      { nombre: "NO PARA EN ESTACIÓN" },
      { nombre: "OTRO" },
      { nombre: "PARADA INCORRECTA" },
      { nombre: "ROTURA DE CATENARIA" },
      { nombre: "TALONAMIENTO" },
    ],
  },
  {
    codigo: "UBICACION_EVENTO",
    nombre: "Ubicación",
    descripcion: "LISTA DE EVENTOS!Ubicación (zona dentro de la estación/tren).",
    items: [
      { nombre: "ANDEN" },
      { nombre: "ASCENSOR" },
      { nombre: "ESCALERA ELÉCTRICA" },
      { nombre: "ESCALERA FIJA" },
      { nombre: "ESCALERA INTERNA" },
      { nombre: "ESTACIÓN" },
      { nombre: "EXPLANADA" },
      { nombre: "HALL" },
      { nombre: "INTERESTACIONAL" },
      { nombre: "PASARELA" },
      { nombre: "PATIO" },
      { nombre: "SERVICIOS HIGIÉNICOS" },
      { nombre: "TREN" },
      { nombre: "ZONA NO PAGA" },
    ],
  },
  {
    codigo: "TIPO_VIA",
    nombre: "Tipo de vía",
    descripcion: "LISTA DE EVENTOS!Tipo de vía.",
    items: [{ nombre: "IMPAR" }, { nombre: "PAR" }],
  },
  {
    codigo: "DIRECCION_VIA",
    nombre: "Dirección de vía",
    descripcion:
      "LISTA DE EVENTOS!Dirección de vía. AVISO: valores 'LEGAL'/'N/A' no parecen describir una dirección de vía — sospecha de columna desalineada en la tabla dinámica del cliente. Sembrado tal cual viene, pendiente de confirmación.",
    items: [{ nombre: "LEGAL" }, { nombre: "N/A" }],
  },
  {
    codigo: "MODELO_MR",
    nombre: "Modelo MR",
    descripcion: "LISTA DE EVENTOS!Modelo MR (material rodante). Coincide con los fabricantes mencionados en la hoja BD (trenes Ansaldo, ALSTOM-BOMBARDIER).",
    items: [{ nombre: "ALSTOM" }, { nombre: "ANSALDO" }, { nombre: "N/A" }],
  },
  {
    codigo: "NUMERO_MR",
    nombre: "Nro. MR",
    descripcion: "LISTA DE EVENTOS!Nro. MR. Unidades T1-T44 + vehículos auxiliares de vía.",
    items: [
      { nombre: "N/A" },
      ...Array.from({ length: 44 }, (_, i) => ({ nombre: `T${i + 1}` })),
      { nombre: "V-BIVIAL" },
      { nombre: "V-DRESINA" },
      { nombre: "V-GRECO" },
      { nombre: "V-GRUA" },
      { nombre: "VH-PLATAFORMA" },
      { nombre: "V-PLATAFORMA" },
    ],
  },
  {
    codigo: "PERSONAL_INVOLUCRADO",
    nombre: "Personal o falla Involucrado",
    descripcion: "LISTA DE EVENTOS!Personal o falla Involucrado.",
    items: [
      { nombre: "AGENTE DE ESTACIÓN" },
      { nombre: "CONDUCTOR" },
      { nombre: "FALLA DE TREN" },
      { nombre: "IOS" },
      { nombre: "JR ABIERTO  Y/O ACAT" },
      { nombre: "JR, ACAT Y/O FRENOS CERRADOS" },
      { nombre: "JR, ACAT Y/OFALTA DE VENTILACIÓN" },
      { nombre: "MR" },
      { nombre: "OTRO" },
      { nombre: "PASAJERO" },
      { nombre: "PERSONAL DE LIMPIEZA" },
      { nombre: "TECNICO" },
      { nombre: "TERCERO" },
      { nombre: "TRANSEUNTE" },
      { nombre: "AVP" },
    ],
  },
  {
    codigo: "TIPO_CAUSA",
    nombre: "Tipo Causa",
    descripcion:
      "LISTA DE EVENTOS!Tipo Causa. AVISO: 'CARRERA COMERCIAL A BAY' no suena a un tipo de causa (parece un dato de servicio/ruta) — misma sospecha de desalineación que 'Dirección de vía'. Sembrado tal cual, pendiente de confirmación.",
    items: [
      { nombre: "CARRERA COMERCIAL A BAY" },
      { nombre: "FACTOR EXTERNO" },
      { nombre: "FALLA OPERACIONAL" },
      { nombre: "FALLA TÉCNICA" },
    ],
  },
  {
    codigo: "POSIBLE_CAUSA",
    nombre: "Posible Causa",
    descripcion:
      "LISTA DE EVENTOS!Posible Causa. Contiene variantes casi-duplicadas del mismo concepto (ej. 'no se cumplio procedimiento' vs 'No cumplió procedimiento o método establecido'; 'Problemas mentales' vs 'Problemas mentales, enfermedades'). Se sembraron todas tal cual el CSV para no perder información; la limpieza/fusión queda pendiente de decisión del cliente.",
    items: [
      { nombre: "Actos delictivos" },
      { nombre: "Amenaza suicida" },
      { nombre: "Caída" },
      { nombre: "Confusión" },
      { nombre: "Cruzar" },
      { nombre: "Distracción" },
      { nombre: "Eléctrico" },
      { nombre: "Empujado" },
      { nombre: "En investigación" },
      { nombre: "Error de humano" },
      { nombre: "Errores de manejo u operación" },
      { nombre: "Estado etílico" },
      { nombre: "Estrés térmico en el punto de contacto" },
      { nombre: "Falla de tren, pedido de Trabajo 656150" },
      { nombre: "Fatiga y somnolencia" },
      { nombre: "Incumplimiento Videa" },
      { nombre: "Intento de suicidio" },
      { nombre: "IOS 225, 245" },
      { nombre: "JR ABIERTO  Y/O ACAT" },
      { nombre: "JR abierto, ACAT y falta de ventilación" },
      { nombre: "Lubricación" },
      { nombre: "Lubricación de curvas" },
      { nombre: "Mala comunicación" },
      { nombre: "Manejo o conducción" },
      { nombre: "Mécanico" },
      { nombre: "Miccionar" },
      { nombre: "No cumplió procedimiento o método establecido" },
      { nombre: "No identificada" },
      { nombre: "no se cumplio procedimiento" },
      { nombre: "Obstrucción" },
      { nombre: "Omisión de procedimientos" },
      { nombre: "Otro" },
      { nombre: "Problemas mentales" },
      { nombre: "Problemas mentales, enfermedades" },
      { nombre: "Recoger objeto" },
      { nombre: "Retiro de animal en la vía" },
      { nombre: "Salida/entrada a destiempo" },
      { nombre: "Salir" },
      { nombre: "Suicidio" },
      { nombre: "Transeunte en la vía" },
      { nombre: "Tropiezo" },
      { nombre: "Uso de celular/ distraído" },
    ],
  },
  {
    codigo: "LUGAR_INCIDENTE",
    nombre: "Lugar de Incidente",
    descripcion:
      "LISTA DE EVENTOS!Lugar de Incidente, con el código de 3 letras (ej. GAM) en 'codigo'. El nombre completo de cada estación (ej. Gamarra) y las 2 entradas de 'Taller' se confirmaron contra la app ya desplegada en sigma-l1-metromet.vercel.app (paso 'Ubicación' del wizard de Reportante), no vienen del CSV.",
    items: [
      { codigo: "VES", nombre: "Villa El Salvador" },
      { codigo: "PIN", nombre: "Parque Industrial" },
      { codigo: "PUM", nombre: "Pumacahua" },
      { codigo: "VMA", nombre: "Villa Maria" },
      { codigo: "MAU", nombre: "Maria Auxiliadora" },
      { codigo: "SJU", nombre: "San Juan" },
      { codigo: "CAB", nombre: "Cabitos" },
      { codigo: "ATO", nombre: "Atocongo" },
      { codigo: "JCH", nombre: "Jorge Chavez" },
      { codigo: "AYA", nombre: "Ayacucho" },
      { codigo: "ANG", nombre: "Angamos" },
      { codigo: "SBS", nombre: "San Borja Sur" },
      { codigo: "CUL", nombre: "La Cultura" },
      { codigo: "NAR", nombre: "Arriola" },
      { codigo: "GAM", nombre: "Gamarra" },
      { codigo: "MIG", nombre: "Miguel Grau" },
      { codigo: "ELA", nombre: "El Angel" },
      { codigo: "PRE", nombre: "Presbitero Maestro" },
      { codigo: "CAA", nombre: "Caja de Agua" },
      { codigo: "PIR", nombre: "Piramide del Sol" },
      { codigo: "JAR", nombre: "Los Jardines" },
      { codigo: "POS", nombre: "Los Postes" },
      { codigo: "SCA", nombre: "San Carlos" },
      { codigo: "SMA", nombre: "San Martin" },
      { codigo: "SRO", nombre: "Santa Rosa" },
      { codigo: "BAY", nombre: "Bayovar" },
      { codigo: "EXTERIORES", nombre: "Exteriores" },
      { nombre: "Taller Villa El Salvador" },
      { nombre: "Taller Bayóvar" },
    ],
  },
  {
    codigo: "TIPO_REPORTE",
    nombre: "Tipo de Reporte",
    descripcion:
      "No viene del CSV — son los 6 valores exactos del paso 'Tipo' del wizard de Reportante ya desplegado en sigma-l1-metromet.vercel.app (más simple que la 'Tipo de incidente operativo' de 20 valores, que es para el registro operativo interno, no para lo que ve el reportante).",
    items: [
      { nombre: "Accidente", descripcion: "Lesión o daño" },
      { nombre: "Incidente", descripcion: "Casi accidente" },
      { nombre: "Condición Insegura", descripcion: "Estado físico" },
      { nombre: "Hallazgo", descripcion: "Detección" },
      { nombre: "Acto Inseguro", descripcion: "Acción de riesgo" },
      { nombre: "Otro", descripcion: "Otro evento" },
    ],
  },
  {
    codigo: "LUGAR_ESPECIFICO",
    nombre: "Lugar Específico",
    descripcion:
      "No viene del CSV — son los 8 valores exactos del paso 'Ubicación' (campo opcional 'Lugar específico') del wizard ya desplegado en sigma-l1-metromet.vercel.app.",
    items: [
      { nombre: "Andén" },
      // El cliente pidió "Coche" en vez de "Vagón" (terminología de Línea 1).
      { nombre: "Coche" },
      { nombre: "Escalera eléctrica" },
      { nombre: "Ascensor" },
      { nombre: "Boletería" },
      { nombre: "Pasillo" },
      { nombre: "Acceso" },
      { nombre: "Otro" },
    ],
  },
];
