-- Módulo Gestión de Planes de Contingencia.
-- Aplicar una vez en cada base de datos antes de usar /api/contingencias.
-- Script aditivo e idempotente: crea tablas, índices, llaves foráneas y rol
-- sin borrar datos existentes.

INSERT INTO "roles" ("nombre_rol")
SELECT 'Gestión de Planes de Contingencia'
WHERE NOT EXISTS (
  SELECT 1 FROM "roles" WHERE "nombre_rol" = 'Gestión de Planes de Contingencia'
);

CREATE TABLE IF NOT EXISTS "contingencia_catalogos" (
  "id_catalogo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR(80) NOT NULL,
  "nombre" VARCHAR(160) NOT NULL,
  "hoja_excel" VARCHAR(80),
  "columna_excel" VARCHAR(10),
  "estado" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "contingencia_catalogo_items" (
  "id_item" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_catalogo" INTEGER NOT NULL,
  "valor" VARCHAR(220) NOT NULL,
  "orden" INTEGER NOT NULL DEFAULT 1,
  "estado" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "contingencia_eventos" (
  "id_evento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_evento" VARCHAR(30),
  "fecha" DATE NOT NULL,
  "hora_reporte" TIME(6),
  "mes" SMALLINT,
  "tipo_evento" VARCHAR(100) NOT NULL,
  "lugar_evento" VARCHAR(160),
  "lugar_exacto_evento" VARCHAR(180),
  "quien_reporta" VARCHAR(120),
  "medio_comunicacion_primer_reporte" VARCHAR(180),
  "estado_usuario_reportado" VARCHAR(80),
  "acepta_atencion" VARCHAR(20),
  "atencion_inicial" VARCHAR(120),
  "atencion_final" VARCHAR(120),
  "nivel_inicial" VARCHAR(60),
  "nivel_final" VARCHAR(60),
  "hora_termino_ae" TIME(6),
  "estado" VARCHAR(30) NOT NULL DEFAULT 'Registrado',
  "created_by" INTEGER,
  "updated_by" INTEGER,
  "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "contingencia_atenciones" (
  "id_atencion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_evento" INTEGER NOT NULL,
  "hora_llamado_pco_sppa" TIME(6),
  "hora_llegada_spaa" TIME(6),
  "hora_inicio_spaa" TIME(6),
  "hora_termino_atencion_inicio_traslado" TIME(6),
  "estacion_partida_spaa" VARCHAR(160),
  "medio_transporte_spaa" VARCHAR(120),
  "trasladado_por" VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS "contingencia_traslados" (
  "id_traslado" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_evento" INTEGER NOT NULL,
  "estacion_partida_ambulancia" VARCHAR(160),
  "estacion_llegada_ambulancia" VARCHAR(180),
  "hora_llamado_ambulancia" TIME(6),
  "hora_llegada_estacion" TIME(6),
  "hora_salida_centro_salud" TIME(6),
  "hora_llegada_centro_medico" TIME(6),
  "hora_retiro_centro_medico" TIME(6),
  "hora_retorno_puesto" TIME(6),
  "hora_llamado_ambulancia_tercero" TIME(6),
  "hora_llegada_ambulancia_terceros" TIME(6),
  "hora_inicio_traslado_ambulancia_terceros" TIME(6),
  "centro_salud" VARCHAR(180)
);

CREATE TABLE IF NOT EXISTS "contingencia_personas" (
  "id_persona" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_evento" INTEGER NOT NULL,
  "nombre_persona" VARCHAR(180),
  "dni" VARCHAR(20),
  "sexo" VARCHAR(10),
  "edad" INTEGER,
  "tarjeta_cliente" VARCHAR(60),
  "categoria_paciente" VARCHAR(120),
  "extranjero" VARCHAR(10),
  "estacion_origen_usuario" VARCHAR(160),
  "estacion_destino_usuario" VARCHAR(160),
  "acompanante" VARCHAR(80),
  "numero_dni_acompanante" VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS "contingencia_diagnosticos" (
  "id_diagnostico" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_evento" INTEGER NOT NULL,
  "reporte_pco" VARCHAR(180),
  "reporte_cliente" VARCHAR(180),
  "diagnostico_presuntivo" VARCHAR(220),
  "sintomas_presentados" TEXT,
  "zona_lesion" VARCHAR(120),
  "nombre_personal_salud" VARCHAR(180),
  "tipo_declaracion_jurada" VARCHAR(20),
  "nro_declaracion_jurada" VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS "contingencia_cierres" (
  "id_cierre" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_evento" INTEGER NOT NULL,
  "breve_descripcion_hecho" TEXT,
  "reserva_camaras" VARCHAR(120),
  "observacion" TEXT,
  "registro" VARCHAR(120),
  "revision" VARCHAR(120),
  "casos_sospechosos_covid_19" VARCHAR(120)
);

CREATE UNIQUE INDEX IF NOT EXISTS "contingencia_catalogos_codigo_key"
  ON "contingencia_catalogos" ("codigo");
CREATE INDEX IF NOT EXISTS "idx_cont_catalogo_estado"
  ON "contingencia_catalogos" ("estado");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_cont_item_catalogo_valor"
  ON "contingencia_catalogo_items" ("id_catalogo", "valor");
CREATE INDEX IF NOT EXISTS "idx_cont_item_catalogo"
  ON "contingencia_catalogo_items" ("id_catalogo");
CREATE INDEX IF NOT EXISTS "idx_cont_item_estado"
  ON "contingencia_catalogo_items" ("estado");

CREATE UNIQUE INDEX IF NOT EXISTS "contingencia_eventos_codigo_evento_key"
  ON "contingencia_eventos" ("codigo_evento");
CREATE INDEX IF NOT EXISTS "idx_cont_evento_fecha"
  ON "contingencia_eventos" ("fecha");
CREATE INDEX IF NOT EXISTS "idx_cont_evento_estado"
  ON "contingencia_eventos" ("estado");
CREATE INDEX IF NOT EXISTS "idx_cont_evento_tipo"
  ON "contingencia_eventos" ("tipo_evento");
CREATE INDEX IF NOT EXISTS "idx_cont_evento_created_by"
  ON "contingencia_eventos" ("created_by");

CREATE UNIQUE INDEX IF NOT EXISTS "contingencia_atenciones_id_evento_key"
  ON "contingencia_atenciones" ("id_evento");
CREATE UNIQUE INDEX IF NOT EXISTS "contingencia_traslados_id_evento_key"
  ON "contingencia_traslados" ("id_evento");
CREATE UNIQUE INDEX IF NOT EXISTS "contingencia_personas_id_evento_key"
  ON "contingencia_personas" ("id_evento");
CREATE INDEX IF NOT EXISTS "idx_cont_persona_categoria"
  ON "contingencia_personas" ("categoria_paciente");
CREATE UNIQUE INDEX IF NOT EXISTS "contingencia_diagnosticos_id_evento_key"
  ON "contingencia_diagnosticos" ("id_evento");
CREATE UNIQUE INDEX IF NOT EXISTS "contingencia_cierres_id_evento_key"
  ON "contingencia_cierres" ("id_evento");

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cont_item_catalogo') THEN
    ALTER TABLE "contingencia_catalogo_items"
      ADD CONSTRAINT "fk_cont_item_catalogo"
      FOREIGN KEY ("id_catalogo") REFERENCES "contingencia_catalogos"("id_catalogo")
      ON DELETE CASCADE ON UPDATE NO ACTION;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cont_atencion_evento') THEN
    ALTER TABLE "contingencia_atenciones"
      ADD CONSTRAINT "fk_cont_atencion_evento"
      FOREIGN KEY ("id_evento") REFERENCES "contingencia_eventos"("id_evento")
      ON DELETE CASCADE ON UPDATE NO ACTION;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cont_traslado_evento') THEN
    ALTER TABLE "contingencia_traslados"
      ADD CONSTRAINT "fk_cont_traslado_evento"
      FOREIGN KEY ("id_evento") REFERENCES "contingencia_eventos"("id_evento")
      ON DELETE CASCADE ON UPDATE NO ACTION;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cont_persona_evento') THEN
    ALTER TABLE "contingencia_personas"
      ADD CONSTRAINT "fk_cont_persona_evento"
      FOREIGN KEY ("id_evento") REFERENCES "contingencia_eventos"("id_evento")
      ON DELETE CASCADE ON UPDATE NO ACTION;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cont_diagnostico_evento') THEN
    ALTER TABLE "contingencia_diagnosticos"
      ADD CONSTRAINT "fk_cont_diagnostico_evento"
      FOREIGN KEY ("id_evento") REFERENCES "contingencia_eventos"("id_evento")
      ON DELETE CASCADE ON UPDATE NO ACTION;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cont_cierre_evento') THEN
    ALTER TABLE "contingencia_cierres"
      ADD CONSTRAINT "fk_cont_cierre_evento"
      FOREIGN KEY ("id_evento") REFERENCES "contingencia_eventos"("id_evento")
      ON DELETE CASCADE ON UPDATE NO ACTION;
  END IF;
END $$;
