-- Tabla para el histórico diario de datos operativos de Monitoreo.
-- Aplicar una vez en cada base de datos antes de usar /api/datos-operativos.
CREATE TABLE IF NOT EXISTS "datos_operativos" (
  "id_dato_operativo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" DATE NOT NULL,
  "qty_carreras" NUMERIC(15, 2) NOT NULL,
  "qty_pasajeros" NUMERIC(15, 2) NOT NULL,
  "km_comercial" NUMERIC(15, 2) NOT NULL,
  "km_no_comercial" NUMERIC(15, 2) NOT NULL,
  "paradas_estacion" NUMERIC(15, 2) NOT NULL,
  "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "datos_operativos_fecha_key"
  ON "datos_operativos" ("fecha");
